// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXMiFPaCcSVFXQN0ho8gwZ2khCfRBmyY',
    appId: '1:1083035074953:android:4d7b70ff2059f1d97d2158',
    messagingSenderId: '1083035074953',
    projectId: 'sphara-flutter-firebase',
    storageBucket: 'sphara-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwZK0i4KrKt_kQs2BxZTGo2tqMkKu5yE8',
    appId: '1:1083035074953:ios:16a1921aeb7327ba7d2158',
    messagingSenderId: '1083035074953',
    projectId: 'sphara-flutter-firebase',
    storageBucket: 'sphara-flutter-firebase.appspot.com',
    androidClientId: '1083035074953-386deogprduoi00d65i8a9rb7kr5010e.apps.googleusercontent.com',
    iosClientId: '1083035074953-4ki76f243vt43bcog49aai77do9o4o0c.apps.googleusercontent.com',
    iosBundleId: 'app.sphara.sphara',
  );
}
